const PDFDocument = require('pdfkit');

const generatePDF = (orders, { title = 'Report', dateFrom, dateTo } = {}) => {
  const doc = new PDFDocument({ margin: 50 });

  // Header
  doc.fontSize(24).fillColor('#031C2E').text('HOOOMANS', { align: 'center' });
  doc.fontSize(14).fillColor('#F2A51A').text(title, { align: 'center' });
  doc.moveDown(0.5);

  if (dateFrom || dateTo) {
    doc.fontSize(10).fillColor('#6B7280').text(
      `Date Range: ${dateFrom || 'Start'} → ${dateTo || 'Now'}`, { align: 'center' }
    );
  }

  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke();
  doc.moveDown(0.5);

  // Summary
  const totalRevenue = orders.reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  const totalOrders = orders.length;

  doc.fontSize(12).fillColor('#1a1a2e')
    .text(`Total Orders: ${totalOrders}`, { continued: true })
    .text(`   |   Total Revenue: ₹${totalRevenue.toLocaleString('en-IN')}`, { align: 'right' });

  doc.moveDown(1);

  // Table header
  const cols = [50, 150, 280, 360, 450, 500];
  doc.fontSize(9).fillColor('#6B7280');
  ['Order ID', 'Customer', 'Amount', 'Status', 'Payment', 'Date'].forEach((h, i) => {
    doc.text(h, cols[i], doc.y, { width: cols[i + 1] ? cols[i + 1] - cols[i] - 5 : 80, lineBreak: false });
  });
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke();
  doc.moveDown(0.3);

  // Rows
  orders.forEach((order, idx) => {
    if (doc.y > 700) { doc.addPage(); }
    const rowColor = idx % 2 === 0 ? '#FFFFFF' : '#F9FAFB';
    const y = doc.y;
    doc.rect(50, y - 2, 495, 18).fill(rowColor).fillColor('#1a1a2e').fontSize(8);
    doc.text(order._id?.toString().slice(-8) || '-', cols[0], y, { width: 95, lineBreak: false });
    doc.text(order.customer?.name || '-', cols[1], y, { width: 125, lineBreak: false });
    doc.text(`₹${(order.totalAmount || 0).toLocaleString('en-IN')}`, cols[2], y, { width: 75, lineBreak: false });
    doc.text(order.status || '-', cols[3], y, { width: 85, lineBreak: false });
    doc.text(order.paymentStatus || '-', cols[4], y, { width: 45, lineBreak: false });
    doc.text(new Date(order.createdAt).toLocaleDateString('en-IN'), cols[5], y, { width: 60, lineBreak: false });
    doc.moveDown(0.7);
  });

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#9CA3AF').text('Generated by HOOOMANS E-Commerce Platform', { align: 'center' });

  return doc;
};

module.exports = { generatePDF };
